In [1]:
import pandas as pd
import numpy as np
import seaborn as sn
import matplotlib.pyplot as mpl

In [2]:
df = pd.read_csv("bank-data.csv")

In [3]:
df

,id,age,sex,region,income,married,children,car,save_act,current_act,mortgage,pep
0,ID12101,48,FEMALE,INNER_CITY,17546.00,NO,1,NO,NO,NO,NO,YES
1,ID12102,40,MALE,TOWN,30085.10,YES,3,YES,NO,YES,YES,NO
2,ID12103,51,FEMALE,INNER_CITY,16575.40,YES,0,YES,YES,YES,NO,NO
3,ID12104,23,FEMALE,TOWN,20375.40,YES,3,NO,NO,YES,NO,NO
4,ID12105,57,FEMALE,RURAL,50576.30,YES,0,NO,YES,NO,NO,NO
...,...,...,...,...,...,...,...,...,...,...,...,...
595,ID12696,61,FEMALE,INNER_CITY,47025.00,NO,2,YES,YES,YES,YES,NO
596,ID12697,30,FEMALE,INNER_CITY,9672.25,YES,0,YES,YES,YES,NO,NO
597,ID12698,31,FEMALE,TOWN,15976.30,YES,0,YES,YES,NO,NO,YES
598,ID12699,29,MALE,INNER_CITY,14711.80,YES,0,NO,YES,NO,YES,NO
599,ID12700,38,MALE,TOWN,26671.60,NO,0,YES,NO,YES,YES,YES

In [4]:
df.head()

,id,age,sex,region,income,married,children,car,save_act,current_act,mortgage,pep
0,ID12101,48,FEMALE,INNER_CITY,17546.0,NO,1,NO,NO,NO,NO,YES
1,ID12102,40,MALE,TOWN,30085.1,YES,3,YES,NO,YES,YES,NO
2,ID12103,51,FEMALE,INNER_CITY,16575.4,YES,0,YES,YES,YES,NO,NO
3,ID12104,23,FEMALE,TOWN,20375.4,YES,3,NO,NO,YES,NO,NO
4,ID12105,57,FEMALE,RURAL,50576.3,YES,0,NO,YES,NO,NO,NO

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           600 non-null    object
 1   age          600 non-null    int64
 2   sex          600 non-null    object
 3   region       600 non-null    object
 4   income       600 non-null    float64
 5   married      600 non-null    object
 6   children     600 non-null    int64
 7   car          600 non-null    object
 8   save_act     600 non-null    object
 9   current_act  600 non-null    object
 10  mortgage     600 non-null    object
 11  pep          600 non-null    object
dtypes: float64(1), int64(2), object(9)
memory usage: 56.4+ KB

In [6]:
df.describe()

              age        income    children
count  600.000000    600.000000  600.000000
mean    42.395000  27524.031217    1.011667
std     14.424947  12899.468246    1.056752
min     18.000000   5014.210000    0.000000
25%     30.000000  17264.500000    0.000000
50%     42.000000  24925.300000    1.000000
75%     55.250000  36172.675000    2.000000
max     67.000000  63130.100000    3.000000

In [7]:
df.isnull()

,id,age,sex,region,income,married,children,car,save_act,current_act,mortgage,pep
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
595,False,False,False,False,False,False,False,False,False,False,False,False
596,False,False,False,False,False,False,False,False,False,False,False,False
597,False,False,False,False,False,False,False,False,False,False,False,False
598,False,False,False,False,False,False,False,False,False,False,False,False
599,False,False,False,False,False,False,False,False,False,False,False,False

In [8]:
df.isnull().sum()

id             0
age            0
sex            0
region         0
income         0
married        0
children       0
car            0
save_act       0
current_act    0
mortgage       0
pep            0
dtype: int64

In [9]:
df.notnull()

,id,age,sex,region,income,married,children,car,save_act,current_act,mortgage,pep
0,True,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...
595,True,True,True,True,True,True,True,True,True,True,True,True
596,True,True,True,True,True,True,True,True,True,True,True,True
597,True,True,True,True,True,True,True,True,True,True,True,True
598,True,True,True,True,True,True,True,True,True,True,True,True
599,True,True,True,True,True,True,True,True,True,True,True,True

In [10]:
df.notnull().sum()

id             600
age            600
sex            600
region         600
income         600
married        600
children       600
car            600
save_act       600
current_act    600
mortgage       600
pep            600
dtype: int64

In [11]:
df.dtypes

id              object
age              int64
sex             object
region          object
income         float64
married         object
children         int64
car             object
save_act        object
current_act     object
mortgage        object
pep             object
dtype: object

In [12]:
df.shape

(600, 12)

In [13]:
df.mean()

age            42.395000
income      27524.031217
children        1.011667
dtype: float64

In [16]:
df['income']=df['income'].astype('str')

In [17]:
df.dtypes

id             object
age             int64
sex            object
region         object
income         object
married        object
children        int64
car            object
save_act       object
current_act    object
mortgage       object
pep            object
dtype: object

In [18]:
df.ndim

2